/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

import javax.swing.JOptionPane;

/**
 *
 * @author Ace
 */
public class adminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminDashboard.class.getName());

    private java.awt.Frame parent;
    /**
     * Creates new form NewJFrame
     */
    public adminDashboard() {
        initComponents();
        PassengerStorage.getInstance().addListener(this::refreshTable);
        refreshTable();
    }
    
    private void refreshTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (PassengerDetails p : PassengerStorage.getInstance().getAllPassengers()) {
        String status = p.getBoardingStatus();
        if ("Boarded".equals(status) || "No-Show".equals(status)) {
            continue; // completed passengers drop off the live dashboard
        }
        model.addRow(new Object[]{
            p.getQueueNumber(), p.getFullName(), p.getAge(), p.getTicketNumber(),
            p.getLuggageCount(), p.getPassengerType(), p.getDestination(), p.getBoardingStatus()
        });
        }
    }
    
    public adminDashboard(java.awt.Frame parent) {
        this();
        this.parent = parent;
    }
    
    private String previousPanel = "adminDashboardPanel";
    private String currentPanel = "adminDashboardPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    adminDashboardPanel.setVisible(false);

    switch (panelName) {
        case "adminDashboardPanel":     adminDashboardPanel.setVisible(true);     break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        adminDashboardPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        passengerDatabaseButton = new javax.swing.JButton();
        auditLogsButton = new javax.swing.JButton();
        userManagementButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jToggleButton1.setText("jToggleButton1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminDashboardPanel.setBackground(new java.awt.Color(0, 51, 102));
        adminDashboardPanel.setForeground(new java.awt.Color(255, 255, 255));
        adminDashboardPanel.setPreferredSize(new java.awt.Dimension(700, 450));
        adminDashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setBackground(new java.awt.Color(255, 204, 0));
        logoutButton.setForeground(new java.awt.Color(0, 51, 102));
        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);
        adminDashboardPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 80, 30));

        passengerDatabaseButton.setBackground(new java.awt.Color(255, 204, 0));
        passengerDatabaseButton.setForeground(new java.awt.Color(0, 51, 102));
        passengerDatabaseButton.setText("<html> View Passanger Database <html>");
        passengerDatabaseButton.addActionListener(this::passengerDatabaseButtonActionPerformed);
        adminDashboardPanel.add(passengerDatabaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 70));

        auditLogsButton.setBackground(new java.awt.Color(255, 204, 0));
        auditLogsButton.setForeground(new java.awt.Color(0, 51, 102));
        auditLogsButton.setText("Audit Logs");
        auditLogsButton.addActionListener(this::auditLogsButtonActionPerformed);
        adminDashboardPanel.add(auditLogsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 60));

        userManagementButton.setBackground(new java.awt.Color(255, 204, 0));
        userManagementButton.setForeground(new java.awt.Color(0, 51, 102));
        userManagementButton.setText("<html>User Management<html>");
        userManagementButton.addActionListener(this::userManagementButtonActionPerformed);
        adminDashboardPanel.add(userManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Queue No.", "Full Name", "Age", "Ticket Number", "Luggage Bags", "Passenger Type", "Destination", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        adminDashboardPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 513, 244));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Call Passenger");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        adminDashboardPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Process Passenger");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        adminDashboardPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 190, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("National Airways");
        adminDashboardPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Dashboard");
        adminDashboardPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 160, 20));

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Live Boarding Queue");
        adminDashboardPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        adminDashboardPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?", "Confirm Logout",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();
        if (parent != null) {
            parent.setVisible(true);
        }
    }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void auditLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditLogsButtonActionPerformed
    this.setVisible(false);
    auditLogs auditlogs = new auditLogs(this);
    auditlogs.setVisible(true);
    }//GEN-LAST:event_auditLogsButtonActionPerformed

    private void passengerDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerDatabaseButtonActionPerformed
    this.setVisible(false);
    passengerDatabase passengerdatabase = new passengerDatabase(this);
    passengerdatabase.setVisible(true);
    }//GEN-LAST:event_passengerDatabaseButtonActionPerformed

    private void userManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementButtonActionPerformed
    this.setVisible(false);
    userManagement usermanagement = new userManagement(this);
    usermanagement.setVisible(true);
    }//GEN-LAST:event_userManagementButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    PassengerStorage storage = PassengerStorage.getInstance();
    PassengerDetails next = storage.getNextWaitingPassenger();

if (next == null) {
    JOptionPane.showMessageDialog(this,
            "No Passengers waiting",
            "Queue Empty",
            JOptionPane.INFORMATION_MESSAGE);
    return;
}

int confirm = JOptionPane.showConfirmDialog(this,
        "Call next passenger: " + next.getFullName() + " (Queue No. " + next.getQueueNumber() + ")?",
        "Confirm Call Passenger",
        JOptionPane.YES_NO_OPTION);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

storage.updateBoardingStatus(next.getQueueNumber(), "Now Boarding");
storage.recordAuditLog("Called passenger \"" + next.getFullName()
        + "\" (Queue No. " + next.getQueueNumber() + ") for boarding.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    PassengerStorage storage = PassengerStorage.getInstance();
    PassengerDetails current = storage.getCurrentBoardingPassenger();

if (current == null) {
    JOptionPane.showMessageDialog(this,
            "No Passenger currently boarding",
            "No Passenger",
            JOptionPane.INFORMATION_MESSAGE);
    return;
}

Object[] options = {"Mark Boarded", "Mark No-Show"};
int choice = JOptionPane.showOptionDialog(this,
        "Now Boarding: " + current.getFullName() + " (Queue No. " + current.getQueueNumber() + ")",
        "Process Passenger",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null, options, options[0]);

if (choice == 0) {
    storage.updateBoardingStatus(current.getQueueNumber(), "Boarded");
    storage.recordAuditLog("Marked passenger \"" + current.getFullName()
            + "\" (Queue No. " + current.getQueueNumber() + ") as Boarded.");

} else if (choice == 1) {
    String reason = JOptionPane.showInputDialog(this,
            "Enter No-Show Reason:",
            "No-Show Reason",
            JOptionPane.PLAIN_MESSAGE);

    if (reason != null) {
    storage.updateBoardingStatus(current.getQueueNumber(), "No-Show");
    storage.setNoShowReason(current.getQueueNumber(), reason.isBlank() ? "N/A" : reason);
    storage.recordAuditLog("Marked passenger \"" + current.getFullName()
            + "\" (Queue No. " + current.getQueueNumber() + ") as No-Show. Reason: " + reason);
    }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminDashboardPanel;
    private javax.swing.JButton auditLogsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton passengerDatabaseButton;
    private javax.swing.JButton userManagementButton;
    // End of variables declaration//GEN-END:variables
}
