/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Ace
 */
public class auditLogs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(auditLogs.class.getName());
    private java.awt.Frame parent;
    
    private TableRowSorter<DefaultTableModel> sorter;
    
    private static int logCounter = 1;
    private static final DefaultTableModel logModel = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Log ID", "Username", "Role", "Action", "Details", "Timestamp"}
    );
    
    public auditLogs() {
        initComponents();
        jTable1.setModel(logModel);
        setupSorter();
    }
    
    public auditLogs(java.awt.Frame parent) {
        this();
        this.parent = parent;
    }
    private void setupSorter() {
        sorter = new TableRowSorter<>(logModel);
    jTable1.setRowSorter(sorter);
    }
    private String previousPanel = "auditLogsPanel";
    private String currentPanel = "auditLogsPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    auditLogsPanel.setVisible(false);

    switch (panelName) {
        case "auditLogsPanel":     auditLogsPanel.setVisible(true);     break;
        
    }
    }
    
    public static void log(String action, String details) {
        String logId = String.format("LOG-%04d", logCounter++);
        
        // Grab dynamic session details if available, otherwise default
        String username = "System"; 
        String role = "Staff";      
        
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        // Adds the row directly to the shared logModel
        logModel.addRow(new Object[]{logId, username, role, action, details, timestamp});
    }
private void applyCombinedFilter() {
        if (sorter == null) return;

        List<RowFilter<Object, Object>> filters = new ArrayList<>();

        String txt = jTextField5.getText().trim();
        if (!txt.isEmpty()) {
            filters.add(RowFilter.regexFilter("(?i)" + txt));
        

        String selectedRole = (String) jComboBox1.getSelectedItem();
        if (selectedRole != null && !selectedRole.equalsIgnoreCase("All")) {
            filters.add(RowFilter.regexFilter("(?i)^" + selectedRole + "$", 2));
        }

        if (filters.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.andFilter(filters));
        }
    }

}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auditLogsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        auditLogsPanel.setBackground(new java.awt.Color(0, 51, 102));
        auditLogsPanel.setMinimumSize(new java.awt.Dimension(700, 450));
        auditLogsPanel.setPreferredSize(new java.awt.Dimension(700, 450));
        auditLogsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Log ID", "Username", "Role", "Action", "Details", "Timestamp"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        auditLogsPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 450, 240));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Admin", "Staff"}));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        auditLogsPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filter by Role:");
        auditLogsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, -1));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        auditLogsPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 178, -1));

        jButton1.setBackground(new java.awt.Color(255, 193, 7));
        jButton1.setForeground(new java.awt.Color(0, 40, 80));
        jButton1.setText("Search");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        auditLogsPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 90, -1));

        jButton2.setBackground(new java.awt.Color(255, 193, 7));
        jButton2.setForeground(new java.awt.Color(0, 40, 80));
        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        auditLogsPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 370, 90, -1));

        jButton3.setBackground(new java.awt.Color(255, 193, 7));
        jButton3.setForeground(new java.awt.Color(0, 40, 80));
        jButton3.setText("Print");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        auditLogsPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 100, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        auditLogsPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 10));

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Audit Logs");
        auditLogsPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(auditLogsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(auditLogsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try {
            jTable1.print();
        } catch (java.awt.print.PrinterException e) {
            JOptionPane.showMessageDialog(this, "Could not print: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
        if (parent != null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
    DefaultTableModel jtbl1 = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(jtbl1);
        
        jTable1.setRowSorter(sorter);
        
        String txt = jTextField5.getText();
        
        if(txt.trim().length()==0){
            sorter.setRowFilter(null);
        }
        else{
            sorter.setRowFilter(RowFilter.regexFilter("(?i)"+txt));
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new auditLogs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auditLogsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
