/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ace
 */
public class loginPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginPanel.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public loginPanel() {
        initComponents();
    }
    
    private String previousPanel = "loginPanel";
    private String currentPanel = "loginPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    loginPanel.setVisible(false);

    switch (panelName) {
        case "loginPanel":     loginPanel.setVisible(true);     break;
        
    }
}
    
    private int attemptsRemaining = 3;
    private int lockCount = 0;
    private long lockUntilMillis = 0;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        footerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        loginPanel.setBackground(new java.awt.Color(0, 51, 102));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Login To National Airways");
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 118, -1, 61));

        UsernameField.addActionListener(this::UsernameFieldActionPerformed);
        loginPanel.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 185, 139, -1));

        loginButton.setText("LOG IN");
        loginButton.addActionListener(this::loginButtonActionPerformed);
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 275, -1, 21));

        PasswordField.addActionListener(this::PasswordFieldActionPerformed);
        loginPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 225, 139, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        loginPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 14, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Username:");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 188, 63, -1));

        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Password:");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 228, 63, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        loginPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 340, 270));

        footerLabel.setForeground(new java.awt.Color(255, 255, 255));
        footerLabel.setText("Safe • Organized • Efficient");
        loginPanel.add(footerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if (System.currentTimeMillis() < lockUntilMillis) {
        long minutesLeft = (lockUntilMillis - System.currentTimeMillis()) / 60000 + 1;
        JOptionPane.showMessageDialog(this, "Account locked. Try again in " + minutesLeft + " minute(s).");
        return;
    }

    String username = UsernameField.getText().trim();
    char[] passwordChars = PasswordField.getPassword();
    String password = new String(passwordChars);

    if (username.isBlank() || password.isBlank()) {
        JOptionPane.showMessageDialog(this, "Required Fields");
        return;
    }

    AccountDetails matched = null;

    if (username.equals("admin") && password.equals("admin123")) {
        matched = new AccountDetails("admin", "admin123", "admin");
    } else {
        for (AccountDetails account : AccountStorage.accounts) {
            if (account.getuserName().equals(username) &&
                    account.getpassWord().equals(password)) {
                matched = account;
                break;
            }
        }
    }

    Arrays.fill(passwordChars, '0');
    
    if (matched != null && !"Active".equalsIgnoreCase(matched.getStatus())) {
    JOptionPane.showMessageDialog(this,
        "This account is inactive. Please contact an administrator to reactivate it.");
    return;
}

    if (matched != null) {
    attemptsRemaining = 3;
    JOptionPane.showMessageDialog(this, "Login Successful!");

    if (matched.getroles().equalsIgnoreCase("admin")) {
        adminDashboard entry = new adminDashboard(this);
        entry.setVisible(true);
    } else {
        staffDashboard entry = new staffDashboard(this);
        entry.setVisible(true);
    }

    UsernameField.setText("");
    PasswordField.setText("");

    this.setVisible(false);
    return;
}
    
    

    attemptsRemaining--;

    if (attemptsRemaining > 0) {
        JOptionPane.showMessageDialog(this,
            "Invalid username and password. Attempts remaining: " + attemptsRemaining);
    } else {
        lockCount++;
        int lockTimeMinutes = lockCount * 3;
        lockUntilMillis = System.currentTimeMillis() + (lockTimeMinutes * 60_000L);
        JOptionPane.showMessageDialog(this, "Account locked for " + lockTimeMinutes + " minutes.");
        attemptsRemaining = 3;
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
    PasswordField.requestFocusInWindow();
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    mainMenu mainmenu = new mainMenu();
    mainmenu.setVisible(true);
    mainmenu.showPanel("mainMenuPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
    loginButtonActionPerformed(evt);
    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
