/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

/**
 *
 * @author Ace
 */
public class mainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainMenu.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public mainMenu() {
        initComponents();
    }
    
    private String previousPanel = "mainMenuPanel";
    private String currentPanel = "mainMenuPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    mainMenuPanel.setVisible(false);

    switch (panelName) {
        case "mainMenuPanel":     mainMenuPanel.setVisible(true);     break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        getQueueButton = new javax.swing.JButton();
        viewBQButton = new javax.swing.JButton();
        systemLabel = new javax.swing.JLabel();
        footerLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        subtitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenuPanel.setBackground(new java.awt.Color(0, 51, 102));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(700, 450));
        mainMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getQueueButton.setBackground(new java.awt.Color(255, 193, 7));
        getQueueButton.setForeground(new java.awt.Color(0, 51, 102));
        getQueueButton.setText("Get Queue");
        getQueueButton.addActionListener(this::getQueueButtonActionPerformed);
        mainMenuPanel.add(getQueueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 159, 53));

        viewBQButton.setBackground(new java.awt.Color(255, 193, 7));
        viewBQButton.setForeground(new java.awt.Color(0, 51, 102));
        viewBQButton.setText("<html>View Boarding Queue<html>");
        viewBQButton.addActionListener(this::viewBQButtonActionPerformed);
        mainMenuPanel.add(viewBQButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 159, 53));

        systemLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        systemLabel.setForeground(new java.awt.Color(255, 193, 7));
        systemLabel.setText("WELCOME TO NATIONAL AIRWAYS");
        mainMenuPanel.add(systemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        footerLabel.setForeground(new java.awt.Color(255, 255, 255));
        footerLabel.setText("Safe • Organized • Efficient");
        mainMenuPanel.add(footerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        signInButton.setBackground(new java.awt.Color(255, 193, 7));
        signInButton.setForeground(new java.awt.Color(0, 51, 102));
        signInButton.setText("Log in");
        signInButton.addActionListener(this::signInButtonActionPerformed);
        mainMenuPanel.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 74, 34));

        subtitleLabel.setForeground(new java.awt.Color(255, 193, 7));
        subtitleLabel.setText("Boarding Management System");
        mainMenuPanel.add(subtitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 193, 7));
        titleLabel.setText("NATIONAL AIRWAYS");
        mainMenuPanel.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        mainMenuPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void getQueueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getQueueButtonActionPerformed
    this.dispose();
    passengerInfo getqueue = new passengerInfo();
    getqueue.setVisible(true);
    getqueue.showPanel("getQueuePanel");
    }//GEN-LAST:event_getQueueButtonActionPerformed

    private void viewBQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBQButtonActionPerformed
    this.dispose();
    queueDisplay boardingPanel = new queueDisplay();
    boardingPanel.setVisible(true);
    boardingPanel.showPanel("boardingQueuePanel");
    }//GEN-LAST:event_viewBQButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        this.dispose();
        loginPanel loginPanel = new loginPanel();
        loginPanel.setVisible(true);
        loginPanel.showPanel("loginPanel");
    }//GEN-LAST:event_signInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footerLabel;
    private javax.swing.JButton getQueueButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel systemLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewBQButton;
    // End of variables declaration//GEN-END:variables
}
