/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

/**
 *
 * @author Ace
 */
public class queueDisplay extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(queueDisplay.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public queueDisplay() {
        initComponents();
        PassengerStorage.getInstance().addListener(this::refreshQueueTables);
        refreshQueueTables();
    }
    
     private void refreshQueueTables() {
    javax.swing.table.DefaultTableModel model1 = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    javax.swing.table.DefaultTableModel model2 = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    model1.setRowCount(0);
    model2.setRowCount(0);

    for (PassengerDetails p : PassengerStorage.getInstance().getAllPassengers()) {
        Object[] row = { p.getQueueNumber(), p.getLuggageStatus(), p.getBoardingStatus() };
        if ("Iloilo International Airport".equals(p.getDestination())) {
            model1.addRow(row);
        } else if ("Cebu International Airport".equals(p.getDestination())) {
            model2.addRow(row);
        }
    }
}
    
    private String previousPanel = "boardingQueuePanel";
    private String currentPanel = "boardingQueuePanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    boardingQueuePanel.setVisible(false);

    switch (panelName) {
        case "boardingQueuePanel":     boardingQueuePanel.setVisible(true);     break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardingQueuePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        boardingQueuePanel.setBackground(new java.awt.Color(0, 51, 102));
        boardingQueuePanel.setPreferredSize(new java.awt.Dimension(700, 450));
        boardingQueuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Queue Number", "Luggage Status", "Boarding Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        boardingQueuePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 562, 140));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Queue Number", "Luggage Status", "Boarding Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        boardingQueuePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 562, 140));

        jButton1.setBackground(new java.awt.Color(255, 193, 7));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        boardingQueuePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 11, 85, -1));

        jLabel1.setForeground(new java.awt.Color(255, 193, 7));
        jLabel1.setText("Cebu International Airport");
        boardingQueuePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 171, -1));

        jLabel2.setForeground(new java.awt.Color(255, 193, 7));
        jLabel2.setText("Iloilo International Airport");
        boardingQueuePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 202, -1));

        jLabel8.setBackground(new java.awt.Color(255, 204, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Passenger Information");
        boardingQueuePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        boardingQueuePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boardingQueuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boardingQueuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    mainMenu mainmenu = new mainMenu();
    mainmenu.setVisible(true);
    mainmenu.showPanel("mainMenuPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new queueDisplay().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardingQueuePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
