/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ace
 */
public class adminLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminLogin.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public adminLogin() {
        initComponents();
    }
    
    private String previousPanel = "loginPanel";
    private String currentPanel = "loginPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    loginPanel.setVisible(false);

    switch (panelName) {
        case "loginPanel":     loginPanel.setVisible(true);     break;
        
    }
}
    
    private int attemptsRemaining = 3;
    private int lockCount = 0;
    private long lockUntilMillis = 0;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login To National Airways");

        UsernameField.setText("jTextField1");
        UsernameField.addActionListener(this::UsernameFieldActionPerformed);

        loginButton.addActionListener(this::loginButtonActionPerformed);

        PasswordField.setText("jPasswordField1");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(loginButton))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernameField)
                            .addComponent(PasswordField))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if (System.currentTimeMillis() < lockUntilMillis) {
        long minutesLeft = (lockUntilMillis - System.currentTimeMillis()) / 60000 + 1;
        JOptionPane.showMessageDialog(this, "Account locked. Try again in " + minutesLeft + " minute(s).");
        return;
    }

    String username = UsernameField.getText().trim();
    char[] passwordChars = PasswordField.getPassword();
    String password = new String(passwordChars);

    if (username.isBlank() || password.isBlank()) {
        JOptionPane.showMessageDialog(this, "Required Fields");
        return;
    }

    AccountDetails matched = null;

    if (username.equals("admin") && password.equals("admin123")) {
        matched = new AccountDetails("admin", "admin123", "admin");
    } else {
        for (AccountDetails account : AccountStorage.accounts) {
            if (account.getuserName().equals(username) &&
                    account.getpassWord().equals(password)) {
                matched = account;
                break;
            }
        }
    }

    Arrays.fill(passwordChars, '0');

    if (matched != null) {
        attemptsRemaining = 3;
        JOptionPane.showMessageDialog(this, "Login Successful!");

        if (matched.getroles().equalsIgnoreCase("admin")) {
            adminDashboard entry = new adminDashboard(this);
            entry.setVisible(true);
        } else {
            staffDashboard entry = new staffDashboard(this);
            entry.setVisible(true);
        }
        this.setVisible(false);
        return;
    }

    attemptsRemaining--;

    if (attemptsRemaining > 0) {
        JOptionPane.showMessageDialog(this,
            "Invalid username and password. Attempts remaining: " + attemptsRemaining);
    } else {
        lockCount++;
        int lockTimeMinutes = lockCount * 3;
        lockUntilMillis = System.currentTimeMillis() + (lockTimeMinutes * 60_000L);
        JOptionPane.showMessageDialog(this, "Account locked for " + lockTimeMinutes + " minutes.");
        attemptsRemaining = 3;
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
