/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

/**
 *
 * @author Ace
 */
public class passengerInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(passengerInfo.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public passengerInfo() {
        initComponents();
    }
    
    private String previousPanel = "getQueuePanel";
    private String currentPanel = "getQueuePanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    getQueuePanel.setVisible(false);

    switch (panelName) {
        case "getQueuePanel": getQueuePanel.setVisible(true); break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        getQueuePanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 450));

        getQueuePanel.setBackground(new java.awt.Color(0, 51, 102));
        getQueuePanel.setForeground(new java.awt.Color(255, 255, 255));
        getQueuePanel.setPreferredSize(new java.awt.Dimension(700, 450));
        getQueuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getQueuePanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 146, 140, 33));

        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        getQueuePanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 248, 140, 33));
        getQueuePanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 197, 140, 33));

        jLabel1.setForeground(new java.awt.Color(0, 40, 80));
        jLabel1.setText("Full Name:");
        getQueuePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 65, -1));

        jLabel2.setForeground(new java.awt.Color(0, 40, 80));
        jLabel2.setText("Age:");
        getQueuePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 30, -1));

        jLabel3.setForeground(new java.awt.Color(0, 40, 80));
        jLabel3.setText("Ticket Number:");
        getQueuePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 256, 91, -1));

        jLabel4.setForeground(new java.awt.Color(0, 40, 80));
        jLabel4.setText("Number of Luggage:");
        getQueuePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 149, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Passenger", "VIP Passenger", "Senior Citizen", "Standby Passenger", "Unaccompanied Minor Passenger" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        getQueuePanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 195, 140, -1));

        jLabel5.setForeground(new java.awt.Color(0, 40, 80));
        jLabel5.setText("Destination:");
        getQueuePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 252, 76, -1));

        jLabel6.setForeground(new java.awt.Color(0, 40, 80));
        jLabel6.setText("Passenger Type:");
        getQueuePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 198, 85, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Bag", "1 Bags", "2 Bags", "3 Bags", "4+ Bags" }));
        getQueuePanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 146, 140, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cebu International Airport", "Iloilo International Airport" }));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);
        getQueuePanel.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 249, 140, -1));

        jButton1.setBackground(new java.awt.Color(255, 193, 7));
        jButton1.setForeground(new java.awt.Color(0, 40, 80));
        jButton1.setText("Get Queue");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getQueuePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 164, 35));

        jButton2.setBackground(new java.awt.Color(255, 193, 7));
        jButton2.setForeground(new java.awt.Color(0, 40, 80));
        jButton2.setText(" Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getQueuePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 85, -1));

        jPanel1.setBackground(new java.awt.Color(255, 193, 7));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getQueuePanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 610, 220));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getQueuePanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 10));

        jLabel7.setBackground(new java.awt.Color(255, 204, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter passenger details to get a boarding queue number");
        getQueuePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 310, 30));

        jLabel8.setBackground(new java.awt.Color(255, 204, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Passenger Information");
        getQueuePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getQueuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(getQueuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String fullName = jTextField1.getText().trim();
        String ageText = jTextField3.getText().trim();
        String ticketNumber = jTextField2.getText().trim();
        String luggageSelection = (String) jComboBox2.getSelectedItem();
        String passengerType = (String) jComboBox1.getSelectedItem();
        String destination = (String) jComboBox3.getSelectedItem();

        if (fullName.isEmpty() || ageText.isEmpty() || ticketNumber.isEmpty()
                || luggageSelection == null || passengerType == null || destination == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please complete all required fields.", "Missing Information",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageText);
            if (age <= 0 || age > 120) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid age.", "Invalid Age",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!TicketValidator.isValidFormat(ticketNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ticket number must follow the format",
                    "Invalid Ticket Number", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!TicketValidator.isValidDate(ticketNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "The date inside the ticket number is not a valid calendar date.",
                    "Invalid Ticket Number", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (PassengerStorage.getInstance().ticketExists(ticketNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "This ticket number has already been used.", "Duplicate Ticket",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int luggageCount = parseLuggageCount(luggageSelection);
        PassengerDetails passenger = new PassengerDetails(fullName, age, ticketNumber, luggageCount, passengerType, destination);
        int queueNumber = PassengerStorage.getInstance().addPassenger(passenger);

        BoardingTicket ticket = new BoardingTicket(this, fullName, ticketNumber, "MNL", destination, queueNumber);
        ticket.setVisible(true);

this.dispose();
        queueDisplay queuedisplay = new queueDisplay();
        queuedisplay.setVisible(true);
        queuedisplay.showPanel("boardingQueuePanel");
    }

    private int parseLuggageCount(String selection) {
        if (selection == null || selection.isEmpty()) return 0;
        char first = selection.charAt(0);
        return Character.isDigit(first) ? Character.getNumericValue(first) : 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    mainMenu mainmenu = new mainMenu();
    mainmenu.setVisible(true);
    mainmenu.showPanel("mainMenuPanel");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new passengerInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel getQueuePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
