/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

import javax.swing.JOptionPane;

/**
 *
 * @author Ace
 */
public class staffDashboardoutdate extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(staffDashboardoutdate.class.getName());

    private java.awt.Frame parent;
    /**
     * Creates new form NewJFrame
     */
    public staffDashboardoutdate() {
        initComponents();
        PassengerStorage.getInstance().addListener(this::refreshTable);
        refreshTable();
    }
    
    public staffDashboardoutdate(java.awt.Frame parent) {
        this();
        this.parent = parent;
    }
    
     private void refreshTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (PassengerDetails p : PassengerStorage.getInstance().getAllPassengers()) {
        String status = p.getBoardingStatus();
        if ("Boarded".equals(status) || "No-Show".equals(status)) {
            continue;
        }
        model.addRow(new Object[]{
            p.getQueueNumber(), p.getFullName(), p.getAge(), p.getTicketNumber(),
            p.getLuggageCount(), p.getPassengerType(), p.getDestination(), p.getBoardingStatus()
        });
        }
    }
    
    private String previousPanel = "adminDashboardPanel";
    private String currentPanel = "adminDashboardPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    adminDashboardPanel.setVisible(false);

    switch (panelName) {
        case "adminDashboardPanel":     adminDashboardPanel.setVisible(true);     break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        adminDashboardPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        passengerDatabaseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setText("Log out");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        passengerDatabaseButton.setText("View Passanger Database");
        passengerDatabaseButton.addActionListener(this::passengerDatabaseButtonActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Queue No.", "Full Name", "Age", "Ticket Number", "Luggage Bags", "Passenger Type", "Destination", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Process Passenger");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton1.setText("Call Passenger");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout adminDashboardPanelLayout = new javax.swing.GroupLayout(adminDashboardPanel);
        adminDashboardPanel.setLayout(adminDashboardPanelLayout);
        adminDashboardPanelLayout.setHorizontalGroup(
            adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(passengerDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336)
                .addComponent(logoutButton))
            .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminDashboardPanelLayout.setVerticalGroup(
            adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passengerDatabaseButton)
                    .addComponent(logoutButton))
                .addGap(18, 18, 18)
                .addGroup(adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?", "Confirm Logout",
            JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();
        if (parent != null) {
            parent.setVisible(true);
        }
    }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void passengerDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerDatabaseButtonActionPerformed
    this.setVisible(false);
    passengerDatabase passengerdatabase = new passengerDatabase(this);
    passengerdatabase.setVisible(true);
    }//GEN-LAST:event_passengerDatabaseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    PassengerStorage storage = PassengerStorage.getInstance();
    PassengerDetails next = storage.getNextWaitingPassenger();

if (next == null) {
    JOptionPane.showMessageDialog(this,
            "No Passengers waiting",
            "Queue Empty",
            JOptionPane.INFORMATION_MESSAGE);
    return;
}

int confirm = JOptionPane.showConfirmDialog(this,
        "Call next passenger: " + next.getFullName() + " (Queue No. " + next.getQueueNumber() + ")?",
        "Confirm Call Passenger",
        JOptionPane.YES_NO_OPTION);

if (confirm != JOptionPane.YES_OPTION) {
    return;
}

storage.updateBoardingStatus(next.getQueueNumber(), "Now Boarding");
storage.recordAuditLog("Called passenger \"" + next.getFullName()
        + "\" (Queue No. " + next.getQueueNumber() + ") for boarding.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    PassengerStorage storage = PassengerStorage.getInstance();
    PassengerDetails current = storage.getCurrentBoardingPassenger();

if (current == null) {
    JOptionPane.showMessageDialog(this,
            "No Passenger currently boarding",
            "No Passenger",
            JOptionPane.INFORMATION_MESSAGE);
    return;
}

Object[] options = {"Mark Boarded", "Mark No-Show"};
int choice = JOptionPane.showOptionDialog(this,
        "Now Boarding: " + current.getFullName() + " (Queue No. " + current.getQueueNumber() + ")",
        "Process Passenger",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null, options, options[0]);

if (choice == 0) {
    storage.updateBoardingStatus(current.getQueueNumber(), "Boarded");
    storage.recordAuditLog("Marked passenger \"" + current.getFullName()
            + "\" (Queue No. " + current.getQueueNumber() + ") as Boarded.");

} else if (choice == 1) {
    String reason = JOptionPane.showInputDialog(this,
            "Enter No-Show Reason:",
            "No-Show Reason",
            JOptionPane.PLAIN_MESSAGE);

    if (reason != null) {
    storage.updateBoardingStatus(current.getQueueNumber(), "No-Show");
    storage.setNoShowReason(current.getQueueNumber(), reason.isBlank() ? "N/A" : reason);
    storage.recordAuditLog("Marked passenger \"" + current.getFullName()
            + "\" (Queue No. " + current.getQueueNumber() + ") as No-Show. Reason: " + reason);
    }
}
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new staffDashboardoutdate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminDashboardPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton passengerDatabaseButton;
    // End of variables declaration//GEN-END:variables
}
