/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Ace
 */
public class adminLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminLogin.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public adminLogin() {
        initComponents();
    }
    
    private String previousPanel = "loginPanel";
    private String currentPanel = "loginPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    loginPanel.setVisible(false);

    switch (panelName) {
        case "loginPanel":     loginPanel.setVisible(true);     break;
        
    }
}
    
    private int attemptsRemaining = 3;
    private int lockCount = 0;
    private long lockUntilMillis = 0;

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        UsernameField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(606, 437));
        setResizable(false);
        getContentPane().setLayout(null);

        loginPanel.setPreferredSize(new java.awt.Dimension(606, 427));
        loginPanel.setLayout(null);

        UsernameField.setText("admin");
        UsernameField.setBorder(null);
        UsernameField.addActionListener(this::UsernameFieldActionPerformed);
        loginPanel.add(UsernameField);
        UsernameField.setBounds(176, 131, 288, 40);

        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(this::loginButtonActionPerformed);
        loginPanel.add(loginButton);
        loginButton.setBounds(262, 285, 80, 30);

        PasswordField.setText("admin123");
        PasswordField.setBorder(null);
        loginPanel.add(PasswordField);
        PasswordField.setBounds(176, 224, 286, 36);

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        loginPanel.add(jButton1);
        jButton1.setBounds(120, 312, 110, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NA LOGIN.jpg"))); // NOI18N
        loginPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        getContentPane().add(loginPanel);
        loginPanel.setBounds(0, 0, 606, 427);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    if (System.currentTimeMillis() < lockUntilMillis) {
        long minutesLeft = (lockUntilMillis - System.currentTimeMillis()) / 60000 + 1;
        JOptionPane.showMessageDialog(this, "Account locked. Try again in " + minutesLeft + " minute(s).");
        return;
    }

    String username = UsernameField.getText().trim();
    char[] passwordChars = PasswordField.getPassword();
    String password = new String(passwordChars);

    if (username.isBlank() || password.isBlank()) {
        JOptionPane.showMessageDialog(this, "Required Fields");
        return;
    }

    AccountDetails matched = null;

    if (username.equals("admin") && password.equals("admin123")) {
        matched = new AccountDetails("admin", "admin123", "admin");
    } else {
        for (AccountDetails account : AccountStorage.accounts) {
            if (account.getuserName().equals(username) &&
                    account.getpassWord().equals(password)) {
                matched = account;
                break;
            }
        }
    }

    Arrays.fill(passwordChars, '0');

    if (matched != null) {
        attemptsRemaining = 3;
        JOptionPane.showMessageDialog(this, "Login Successful!");

        if (matched.getroles().equalsIgnoreCase("admin")) {
            adminDashboard entry = new adminDashboard(this);
            entry.setVisible(true);
        } else {
            staffDashboard entry = new staffDashboard(this);
            entry.setVisible(true);
        }
        this.setVisible(false);
        return;
    }

    attemptsRemaining--;

    if (attemptsRemaining > 0) {
        JOptionPane.showMessageDialog(this,
            "Invalid username and password. Attempts remaining: " + attemptsRemaining);
    } else {
        lockCount++;
        int lockTimeMinutes = lockCount * 3;
        lockUntilMillis = System.currentTimeMillis() + (lockTimeMinutes * 60_000L);
        JOptionPane.showMessageDialog(this, "Account locked for " + lockTimeMinutes + " minutes.");
        attemptsRemaining = 3;
    }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    mainMenu mainmenu = new mainMenu();
    mainmenu.setVisible(true);
    mainmenu.showPanel("mainMenuPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
