/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

/**
 *
 * @author Ace
 */
public class mainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainMenu.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public mainMenu() {
        initComponents();
    }
    
    private String previousPanel = "mainMenuPanel";
    private String currentPanel = "mainMenuPanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    mainMenuPanel.setVisible(false);

    switch (panelName) {
        case "mainMenuPanel":     mainMenuPanel.setVisible(true);     break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        getQueueButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        viewBQButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(606, 427));
        setPreferredSize(new java.awt.Dimension(606, 437));
        getContentPane().setLayout(null);

        mainMenuPanel.setMinimumSize(new java.awt.Dimension(606, 427));
        mainMenuPanel.setLayout(null);

        getQueueButton.setBorder(null);
        getQueueButton.setBorderPainted(false);
        getQueueButton.setContentAreaFilled(false);
        getQueueButton.addActionListener(this::getQueueButtonActionPerformed);
        mainMenuPanel.add(getQueueButton);
        getQueueButton.setBounds(410, 83, 110, 110);

        signInButton.setBorder(null);
        signInButton.setBorderPainted(false);
        signInButton.setContentAreaFilled(false);
        signInButton.addActionListener(this::signInButtonActionPerformed);
        mainMenuPanel.add(signInButton);
        signInButton.setBounds(510, 10, 60, 30);

        viewBQButton.setBorder(null);
        viewBQButton.setBorderPainted(false);
        viewBQButton.setContentAreaFilled(false);
        viewBQButton.addActionListener(this::viewBQButtonActionPerformed);
        mainMenuPanel.add(viewBQButton);
        viewBQButton.setBounds(410, 240, 110, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NA MAIN MENU.jpg"))); // NOI18N
        mainMenuPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        getContentPane().add(mainMenuPanel);
        mainMenuPanel.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
    this.dispose();
    adminLogin loginPanel = new adminLogin();
    loginPanel.setVisible(true);
    loginPanel.showPanel("loginPanel");
    }//GEN-LAST:event_signInButtonActionPerformed

    private void getQueueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getQueueButtonActionPerformed
    this.dispose();
    passengerInfo getqueue = new passengerInfo();
    getqueue.setVisible(true);
    getqueue.showPanel("getQueuePanel");
    }//GEN-LAST:event_getQueueButtonActionPerformed

    private void viewBQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBQButtonActionPerformed
    this.dispose();
    queueDisplay boardingPanel = new queueDisplay();
    boardingPanel.setVisible(true);
    boardingPanel.showPanel("boardingQueuePanel");
    }//GEN-LAST:event_viewBQButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getQueueButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton viewBQButton;
    // End of variables declaration//GEN-END:variables
}
