/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.national_airways;

/**
 *
 * @author Ace
 */
public class passengerInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(passengerInfo.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public passengerInfo() {
        initComponents();
    }
    
    private String previousPanel = "getQueuePanel";
    private String currentPanel = "getQueuePanel";
    
    public void showPanel(String panelName) {
        
    previousPanel = currentPanel;
    currentPanel = panelName;
    
    getQueuePanel.setVisible(false);

    switch (panelName) {
        case "getQueuePanel": getQueuePanel.setVisible(true); break;
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        getQueuePanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(606, 437));
        getContentPane().setLayout(null);

        getQueuePanel.setLayout(null);

        jTextField1.setBorder(null);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        getQueuePanel.add(jTextField1);
        jTextField1.setBounds(46, 132, 259, 23);

        jTextField2.setBorder(null);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        getQueuePanel.add(jTextField2);
        jTextField2.setBounds(45, 216, 260, 24);

        jTextField3.setBorder(null);
        getQueuePanel.add(jTextField3);
        jTextField3.setBounds(340, 132, 76, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Passenger", "VIP Passenger", "Senior Citizen", "Standby Passenger", "Unaccompanied Minor Passenger" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        getQueuePanel.add(jComboBox1);
        jComboBox1.setBounds(340, 216, 221, 23);
        jComboBox1.getAccessibleContext().setAccessibleDescription("");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Bag", "2 Bags", "3 Bags", "4+ Bags" }));
        jComboBox2.setBorder(null);
        getQueuePanel.add(jComboBox2);
        jComboBox2.setBounds(340, 300, 108, 24);
        jComboBox2.getAccessibleContext().setAccessibleName("");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cebu International Airport", "Iloilo International Airport" }));
        jComboBox3.setBorder(null);
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);
        getQueuePanel.add(jComboBox3);
        jComboBox3.setBounds(46, 300, 259, 24);

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getQueuePanel.add(jButton1);
        jButton1.setBounds(244, 352, 118, 40);

        jButton2.setText("Prev Panel");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getQueuePanel.add(jButton2);
        jButton2.setBounds(10, 370, 85, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NA GET QUEUE.jpg"))); // NOI18N
        getQueuePanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 606, 427);

        getContentPane().add(getQueuePanel);
        getQueuePanel.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String fullName = jTextField1.getText().trim();
        String ageText = jTextField3.getText().trim();
        String ticketNumber = jTextField2.getText().trim();
        String luggageSelection = (String) jComboBox2.getSelectedItem();
        String passengerType = (String) jComboBox1.getSelectedItem();
        String destination = (String) jComboBox3.getSelectedItem();

        if (fullName.isEmpty() || ageText.isEmpty() || ticketNumber.isEmpty()
                || luggageSelection == null || passengerType == null || destination == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please complete all required fields.", "Missing Information",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageText);
            if (age <= 0 || age > 120) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please enter a valid age.", "Invalid Age",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!TicketValidator.isValidFormat(ticketNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ticket number must follow the format AAA-YYYYMMDD-####\nExample: PAL-20260816-0001",
                    "Invalid Ticket Number", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!TicketValidator.isValidDate(ticketNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "The date inside the ticket number is not a valid calendar date.",
                    "Invalid Ticket Number", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (PassengerStorage.getInstance().ticketExists(ticketNumber)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "This ticket number has already been used.", "Duplicate Ticket",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int luggageCount = parseLuggageCount(luggageSelection);
        PassengerDetails passenger = new PassengerDetails(fullName, age, ticketNumber, luggageCount, passengerType, destination);
        int queueNumber = PassengerStorage.getInstance().addPassenger(passenger);

        BoardingTicket ticket = new BoardingTicket(this, fullName, ticketNumber, "MNL", destination, queueNumber);
        ticket.setVisible(true);

this.dispose();
        queueDisplay queuedisplay = new queueDisplay();
        queuedisplay.setVisible(true);
        queuedisplay.showPanel("boardingQueuePanel");
    }

    private int parseLuggageCount(String selection) {
        if (selection == null || selection.isEmpty()) return 0;
        char first = selection.charAt(0);
        return Character.isDigit(first) ? Character.getNumericValue(first) : 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    mainMenu mainmenu = new mainMenu();
    mainmenu.setVisible(true);
    mainmenu.showPanel("mainMenuPanel");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new passengerInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel getQueuePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
